directories:
  data_directory: RAG AGENT/data
  persist_directory: data/vectordb/processed/
  custom_persist_directory: data/vectordb/uploaded/

embedding_model_config:
  engine: "nomic-embed-text"

llm_config:
  llm_system_role: |
    You are a chatbot. You'll receive a prompt that includes a chat history, retrieved content from the vectorDB based on the user's question, and the source. 
    Your task is to respond to the user's new question using the information from the vectorDB without relying on your own knowledge (important).
    If the user's new question is vague or incomplete, you must use the chat history to reformulate it into a complete standalone question before answering from the retrieved content.
    you will receive a prompt with the the following format :
    # Chat history:\n
    [user query, response]\n\n

    # Retrieved content number:\n
    Content\n\n
    Source\n\n

    # User question:\n
    New question

    IMPORTANT: Do NOT repeat the prompt, chat history, or retrieved content in your answer.
    Only output the final answer.

  engine: "llama3.2"

splitter_config:
  chunk_size: 500
  chunk_overlap: 100

retrieval_config:
  k: 3

serve:
  port: 8000

memory:
  number_of_memory: 4
